### ISSUE TITLE
COMI erroring out: received signal SIGBUS, Bus error

### ISSUE THREAD

**Issue by mrfixit2001** [diablodiab/scummvm#7]
Curse of Monkey Island won't load, returns "bus error". Renders the initial screen and then crashes.

GDB backtrace:

```
User picked target 'comi' (engine ID 'scumm', game ID 'comi')...
   Looking for a plugin supporting this target... SCUMM [all games]

Thread 1 "retroarch" received signal SIGBUS, Bus error.
0xefc4de98 in Scumm::IMuseDigital::dispatchCheckForJump(int*, Scumm::IMuseDigiStreamZone*, int&) ()
   from /usr/lib/libretro/scummvm_libretro.so
(gdb) thread apply all bt

Thread 7 (Thread 0xec7ff340 (LWP 16737)):
#0  0xf588a00c in poll () from /lib/libc.so.6
#1  0xf76b8ee8 in snd1_pcm_wait_nocheck () from /usr/lib/libasound.so.2
#2  0xf76bc438 in snd1_pcm_write_areas () from /usr/lib/libasound.so.2
#3  0x0093103c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 6 (Thread 0xed15c340 (LWP 16736)):
#0  0xf5858de8 in ?? () from /lib/libc.so.6
#1  0xf5858e4c in clock_nanosleep () from /lib/libc.so.6
#2  0xf585ea6c in nanosleep () from /lib/libc.so.6
#3  0xf720ced8 in ?? () from /usr/lib/libSDL2-2.0.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 5 (Thread 0xeed90ac0 (LWP 16735)):
#0  0xf57f1098 in sigtimedwait () from /lib/libc.so.6
#1  0xf77aac1c in ?? () from /lib/librt.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 4 (Thread 0xeebff340 (LWP 16734)):
#0  0xf588c558 in ioctl () from /lib/libc.so.6
#1  0xf72da310 in ?? () from /usr/lib/libmali.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
--Type <RET> for more, q to quit, c to continue without paging--

Thread 3 (Thread 0xef592340 (LWP 16712)):
#0  0xf588a00c in poll () from /lib/libc.so.6
#1  0xf72072dc in ?? () from /usr/lib/libSDL2-2.0.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0xf46b6340 (LWP 16711)):
#0  0xf7418ea4 in pthread_cond_wait@@GLIBC_2.4 () from /lib/libpthread.so.0
#1  0x00046c68 in threaded_worker ()
#2  0x00246b88 in thread_wrap ()
#3  0xf7411d4c in start_thread () from /lib/libpthread.so.0
#4  0xf58938c8 in ?? () from /lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0xf77e1f40 (LWP 16708)):
#0  0xefc4de98 in Scumm::IMuseDigital::dispatchCheckForJump(int*, Scumm::IMuseDigiStreamZone*, int&) () from /usr/lib/libretro/scummvm_libretro.so
#1  0xefc4edac in Scumm::IMuseDigital::dispatchPredictStream(Scumm::IMuseDigiDispatch*) () from /usr/lib/libretro/scummvm_libretro.so
#2  0xefc4ee5c in Scumm::IMuseDigital::dispatchPredictFirstStream() () from /usr/lib/libretro/scummvm_libretro.so
#3  0xefc521c8 in Scumm::IMuseDigital::tracksCallback() () from /usr/lib/libretro/scummvm_libretro.so
#4  0xefb23a10 in Scumm::IMuseDigital::waveOutCallback() () from /usr/lib/libretro/scummvm_libretro.so
--Type <RET> for more, q to quit, c to continue without paging--
#5  0xefb196fc in Scumm::IMuseDigital::diMUSEHeartbeat() () from /usr/lib/libretro/scummvm_libretro.so
#6  0xefb19a20 in Scumm::IMuseDigital::callback() () from /usr/lib/libretro/scummvm_libretro.so
#7  0xf23e872c in DefaultTimerManager::handler() () from /usr/lib/libretro/scummvm_libretro.so
#8  0xefab6e50 in virtual thunk to OSystem_RETRO::delayMillis(unsigned int) () from /usr/lib/libretro/scummvm_libretro.so
#9  0xefaf6ba4 in Scumm::ScummEngine::waitForTimer(int) () from /usr/lib/libretro/scummvm_libretro.so
#10 0xefaf6d24 in Scumm::ScummEngine::go() () from /usr/lib/libretro/scummvm_libretro.so
#11 0xefafd0b8 in Scumm::ScummEngine::run() () from /usr/lib/libretro/scummvm_libretro.so
#12 0xefabbbfc in runGame(Plugin const*, Plugin const*, OSystem&, Common::String const&) () from /usr/lib/libretro/scummvm_libretro.so
#13 0xefabde98 in scummvm_main () from /usr/lib/libretro/scummvm_libretro.so
#14 0xefab34d8 in retro_wrap_emulator() () from /usr/lib/libretro/scummvm_libretro.so
#15 0xefab44e4 in retro_run () from /usr/lib/libretro/scummvm_libretro.so
#16 0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

```

**Comment by mrfixit2001** [comment]
I've resolved this on my own... although I have a feeling this is more of a workaround than fixing the underlying issue, so I'll leave this open for now. It's not fixed in scummvm master either.

```
--- dimuse_dispatch.cpp
+++ dimuse_dispatch.cpp
@@ -20,6 +20,7 @@
  *
  */
 
+#include <unistd.h>
 #include "scumm/imuse_digi/dimuse_engine.h"
 #include "scumm/imuse_digi/dimuse_defs.h"
 
@@ -1307,10 +1308,12 @@
 		mapPlaceTag = curMapPlace[0];
 		bytesUntilNextPlace = curMapPlace[1] + 8;
 
+		// Fix bus error
+		usleep(100);
+
 		if (mapPlaceTag == MKTAG('J', 'U', 'M', 'P')) {
 			jumpHookPos = curMapPlace[2];
 			jumpHookId = curMapPlace[4];
-
 			if (jumpHookPos > strZnPtr->offset && jumpHookPos <= strZnPtr->size + strZnPtr->offset) {
 				if (!checkHookId(candidateHookId, jumpHookId))
 					return curMapPlace;
```

**Comment by i30817** [comment]
Did you report it upstream? I know scummvm tracker isn't the most usable ever (just like dolphin), but it's important that upstream bugs get reported upstream.

I'm always annoyed when a big project has no github issue report page. Yeah, i know that keeping the bug tracker a bit unavailable will increase the quality of bug reports and defuse some trolls, but it's still annoying.

In your case you could 'simply' open a PR in their github page to make them aware of the SNAFU.
